// packages/client/modules/renderer/src/uikit/common/components/animations/animated-arrow-overlay/animated-arrow-overlay.component.tsx
import * as C from './animated-arrow-overlay.styles';
import { Assets } from './assets';
import { useEffect, useRef, useState, type FC } from 'react';
import { useResizeObserver } from '@/uikit/core/hooks';

export interface AnimatedArrowOverlayProps {
  isCarrot?: boolean;
  className?: string;
}

export const AnimatedArrowOverlay: FC<AnimatedArrowOverlayProps> = ({
  isCarrot,
  className,
}) => {
  const animatedArrowOverlayWrapper = useRef<HTMLDivElement | null>(null);
  const [path, setPath] = useState<string>('');
  const { width } = useResizeObserver(animatedArrowOverlayWrapper);

  useEffect(() => {
    if (!animatedArrowOverlayWrapper.current) {
      setPath('');
      return;
    }

    const w = width - 31;
    if (isCarrot) {
      setPath(`M0, 0 h${w} l15 16 l-15 16 H0 0,0 Z`);
      return;
    }

    setPath(
      `M0, 0 h${w} l15 16 l-15 16 H0 a21.461 21.461,0,0,0,8.4 -16,21.461 21.461,0,0,0,-8.4 -16 Z`,
    );
  }, [animatedArrowOverlayWrapper, isCarrot, width]);

  return (
    <C.Container className={className}>
      <C.AnimatedArrowOverlayWrapper ref={animatedArrowOverlayWrapper}>
        <svg
          id="path-defs"
          className="svg-container"
          xmlns="http://www.w3.org/2000/svg"
          xmlnsXlink="http://www.w3.org/1999/xlink"
          x="0"
          y="0"
          width="100%"
          height="100%"
        >
          <defs>
            <pattern
              id="noise-map"
              x="0"
              y="0"
              width="400"
              height="40"
              patternUnits="userSpaceOnUse"
            >
              <image
                xlinkHref={Assets.noiseTileAlphaTintLarge}
                x="0"
                y="0"
                width="400"
                height="40"
              />
              <animate
                dur="20s"
                repeatCount="indefinite"
                attributeName="y"
                values="0;20;0"
              />
              <animate
                dur="40s"
                repeatCount="indefinite"
                attributeName="x"
                values="0;50;0;-50;0"
              />
            </pattern>
            <pattern
              id="noise-map-offset"
              x="25%"
              y="0"
              width="400"
              height="40"
              patternUnits="userSpaceOnUse"
            >
              <image
                xlinkHref={Assets.noiseTileAlphaTintLarge}
                x="0"
                y="0"
                width="400"
                height="40"
              />
              <animate
                dur="20s"
                repeatCount="indefinite"
                attributeName="y"
                values="0;20;0"
              />
              <animate
                dur="40s"
                repeatCount="indefinite"
                attributeName="x"
                values="25;75;25;-25;25"
              />
            </pattern>
            <path
              id="scalable-path"
              d={path}
              fill="none"
              stroke="#fff"
              strokeWidth="2"
            />
            <mask
              id="mask-dashed-border"
              maskUnits="userSpaceOnUse"
              x="0"
              y="0"
              width="100%"
              height="100%"
            >
              <use
                className="dashed-border"
                xlinkHref="#scalable-path"
                strokeWidth="4"
              />
            </mask>
            <mask
              id="mask-dashed-border-offset"
              maskUnits="userSpaceOnUse"
              x="0"
              y="0"
            >
              <use
                className="dashed-border offset"
                xlinkHref="#scalable-path"
                strokeWidth="4"
              />
            </mask>
          </defs>
        </svg>

        <div id="animated-magic-container">
          <svg
            id="animated-magic-low"
            className="svg-container"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
            x="0"
            y="0"
            width="100%"
            height="100%"
          >
            <rect
              x="0"
              y="0"
              width="100%"
              height="100%"
              mask="url(#mask-dashed-border)"
              fill="url(#noise-map)"
            />
            <rect
              x="0"
              y="0"
              width="100%"
              height="100%"
              mask="url(#mask-dashed-border-offset)"
              fill="url(#noise-map-offset)"
            />
          </svg>
          <svg
            id="animated-magic-high"
            className="svg-container"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
            x="0"
            y="0"
            width="100%"
            height="100%"
          >
            <rect
              x="0"
              y="0"
              width="100%"
              height="100%"
              mask="url(#mask-dashed-border)"
              fill="url(#noise-map)"
            />
            <rect
              x="0"
              y="0"
              width="100%"
              height="100%"
              mask="url(#mask-dashed-border-offset)"
              fill="url(#noise-map-offset)"
            />
          </svg>
        </div>
      </C.AnimatedArrowOverlayWrapper>
    </C.Container>
  );
};

// packages/client/modules/renderer/src/uikit/common/components/animations/animated-arrow-overlay/AnimatedArrowOverlay.vue
<script lang="ts" setup>
import { computed, ref } from 'vue';
import { useResizeObserver } from '@vueuse/core';
import alphaTint from './assets/images/noise-tile-alpha-tint-large.png';

const props = defineProps<{ isCarrot?: boolean }>();
const containerRef = ref<HTMLDivElement | null>(null);
const width = ref(0);

useResizeObserver(containerRef, (entries) => {
  const rect = entries[0].contentRect;
  width.value = rect.width;
});

const path = computed(() => {
  if (!containerRef.value || !width.value) {
    return '';
  }

  const w = width.value - 31;

  if (props.isCarrot) {
    return `M0, 0 h${w} l15 16 l-15 16 H0 0,0 Z`;
  }

  return `M0, 0 h${w} l15 16 l-15 16 H0 a21.461 21.461,0,0,0,8.4 -16,21.461 21.461,0,0,0,-8.4 -16 Z`;
});
</script>

<template>
  <div ref="containerRef" class="animated-arrow-overlay-container">
    <div class="animated-arrow-overlay-wrapper">
      <svg
        id="path-defs"
        class="svg-container"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        x="0"
        y="0"
        width="100%"
        height="100%"
      >
        <defs>
          <pattern
            id="noise-map"
            x="0"
            y="0"
            width="400"
            height="40"
            patternUnits="userSpaceOnUse"
          >
            <image
              :xlink:href="alphaTint"
              x="0"
              y="0"
              width="400"
              height="40"
            />
            <animate
              dur="20s"
              repeatCount="indefinite"
              attributeName="y"
              values="0;20;0"
            />
            <animate
              dur="40s"
              repeatCount="indefinite"
              attributeName="x"
              values="0;50;0;-50;0"
            />
          </pattern>
          <pattern
            id="noise-map-offset"
            x="25%"
            y="0"
            width="400"
            height="40"
            patternUnits="userSpaceOnUse"
          >
            <image
              :xlink:href="alphaTint"
              x="0"
              y="0"
              width="400"
              height="40"
            />
            <animate
              dur="20s"
              repeatCount="indefinite"
              attributeName="y"
              values="0;20;0"
            />
            <animate
              dur="40s"
              repeatCount="indefinite"
              attributeName="x"
              values="25;75;25;-25;25"
            />
          </pattern>
          <path
            id="scalable-path"
            :d="path"
            fill="none"
            stroke="#fff"
            stroke-width="2"
          />
          <mask
            id="mask-dashed-border"
            maskUnits="userSpaceOnUse"
            x="0"
            y="0"
            width="100%"
            height="100%"
          >
            <use
              xlink:href="#scalable-path"
              stroke-width="4"
              class="dashed-border"
            />
          </mask>
          <mask
            id="mask-dashed-border-offset"
            maskUnits="userSpaceOnUse"
            x="0"
            y="0"
          >
            <use
              xlink:href="#scalable-path"
              stroke-width="4"
              class="dashed-border offset"
            />
          </mask>
        </defs>
      </svg>

      <div id="animated-magic-container">
        <svg
          id="animated-magic-low"
          class="svg-container"
          xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          x="0"
          y="0"
          width="100%"
          height="100%"
        >
          <rect
            x="0"
            y="0"
            width="100%"
            height="100%"
            mask="url(#mask-dashed-border)"
            fill="url(#noise-map)"
          />
          <rect
            x="0"
            y="0"
            width="100%"
            height="100%"
            mask="url(#mask-dashed-border-offset)"
            fill="url(#noise-map-offset)"
          />
        </svg>
        <svg
          id="animated-magic-high"
          class="svg-container"
          xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          x="0"
          y="0"
          width="100%"
          height="100%"
        >
          <rect
            x="0"
            y="0"
            width="100%"
            height="100%"
            mask="url(#mask-dashed-border)"
            fill="url(#noise-map)"
          />
          <rect
            x="0"
            y="0"
            width="100%"
            height="100%"
            mask="url(#mask-dashed-border-offset)"
            fill="url(#noise-map-offset)"
          />
        </svg>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.parent:hover,
.parent:focus-visible {
  .animated-arrow-overlay-wrapper {
    .dashed-border {
      animation-duration: 1500ms;
    }

    #animated-magic-container {
      opacity: 1;
    }
  }
}

.parent:active {
  .animated-arrow-overlay-wrapper {
    .dashed-border {
      animation-duration: 750ms;
    }

    #animated-magic-container {
      opacity: 1;
    }
  }
}

.animated-arrow-overlay-container {
  width: calc(100% + 16px) !important;
  height: calc(100% + 16px) !important;
  left: -8px;
  top: -8px;
  position: absolute;
  cursor: default;
  pointer-events: none;
}

.animated-arrow-overlay-wrapper {
  width: 100%;
  height: 100%;
  position: relative;

  #animated-magic-low {
    filter: blur(2px) contrast(1.15);
    opacity: 0.75;
  }

  #animated-magic-high {
    filter: blur(4px) contrast(1.35) brightness(1.5);
    opacity: 0.85;
  }

  .svg-container {
    position: absolute;
    left: 0;
    top: 0;
  }

  .dashed-border {
    stroke: #fff;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
    animation-duration: 0ms;
    stroke-dasharray: 50;
    animation-name: dashStrokeAnimation;

    &.offset {
      stroke-dashoffset: -50;
      animation-name: dashStrokeOffsetAnimation;
    }
  }

  #scalable-path {
    transform: translate(8px, 8px);
  }

  #animated-magic-container {
    width: 100%;
    height: 100%;
    position: absolute;
    opacity: 0;
    transition: opacity 300ms linear;
  }
}

@keyframes dashStrokeAnimation {
  to {
    stroke-dashoffset: -100;
  }
}

@keyframes dashStrokeOffsetAnimation {
  to {
    stroke-dashoffset: -150;
  }
}
</style>
