// packages/client/modules/renderer/src/uikit/summoner/components/banners/summoner-banner/SummonerBanner.vue
<script lang="ts" setup>
import type { Rank } from '@/types';
import { onUnmounted, ref, watchEffect } from 'vue';
import bannerAlly from './assets/videos/banner_ally.webm';
import bannerPrimary from './assets/videos/banner_primary.webm';
import { AnimatedBanner } from '../animated-banner';

const props = defineProps<{
  bannerType: 'ally' | 'primary';
  rank: Rank;
  showPattern?: boolean;
  playIntro?: boolean;
}>();

const bannerIntroRef = ref<HTMLVideoElement | null>(null);
const introTimeElapsed = ref(false);
const introTimeElapsedTimeout = ref<number | null>(null);
const introState = ref<'LOADING' | 'LOADED' | 'PLAYING' | 'ENDED'>('LOADING');

watchEffect(() => {
  if (!bannerIntroRef.value) {
    return;
  }

  if (introState.value === 'LOADED') {
    if (props.playIntro) {
      bannerIntroRef.value.currentTime = 0;
      bannerIntroRef.value.play();
      const timeout = window.setTimeout(() => {
        introTimeElapsed.value = true;
        introTimeElapsedTimeout.value = null;
      }, 400);
      introTimeElapsedTimeout.value = timeout;
      introState.value = 'PLAYING';
    } else if (!introTimeElapsedTimeout.value) {
      const timeout = window.setTimeout(() => {
        introTimeElapsed.value = true;
        introTimeElapsedTimeout.value = null;
      }, 100);
      introTimeElapsedTimeout.value = timeout;
    }
  } else if (introState.value === 'ENDED') {
    bannerIntroRef.value.currentTime = 0;
  }
});

onUnmounted(() => {
  if (introTimeElapsedTimeout.value) {
    clearTimeout(introTimeElapsedTimeout.value);
  }
});
</script>

<template>
  <div class="summoner-banner">
    <div :class="[{ show: introTimeElapsed || !playIntro }, 'fade-condition']">
      <AnimatedBanner :rank="rank" :show-pattern="showPattern" />
    </div>
    <div
      :class="[
        { show: !!playIntro && introState !== 'ENDED' },
        'fade-condition',
      ]"
    >
      <video
        ref="bannerIntroRef"
        :src="bannerType === 'primary' ? bannerPrimary : bannerAlly"
        muted
        @loadeddata="introState = 'LOADED'"
        @ended="introState = 'ENDED'"
      />
    </div>
  </div>
</template>

<style lang="scss" scoped>
.summoner-banner {
  width: 275px;
  min-width: 100%;
  display: grid;

  &.ally {
    width: 240px;

    video {
      margin-top: -68px;
    }
  }

  .fade-condition {
    grid-column: 1;
    grid-row: 1;
  }

  video {
    margin-top: -60px;
  }

  canvas {
    margin-top: -100px;
  }
}

.fade-condition {
  transition: opacity 300ms ease-in-out;
  opacity: 0;

  &.show {
    opacity: 1;
  }

  display: flex;
  justify-content: center;
}
</style>

// packages/client/modules/renderer/src/uikit/summoner/components/banners/summoner-banner/summoner-banner.component.tsx
import * as C from './summoner-banner.styles';
import { BannerBase } from '../banner-base';
import { Videos } from './assets';
import { useEffect, useRef, useState } from 'react';
import classNames from 'classnames';
import type { FC } from 'react';
import type { Rank } from '@/types';

export type SummonerBannerType = 'primary' | 'ally';

export interface SummonerBannerProps {
  rank: Rank;
  showPattern?: boolean;
  bannerType?: SummonerBannerType;
  playIntro?: boolean;
}

export const SummonerBanner: FC<SummonerBannerProps> = ({
  rank,
  showPattern,
  bannerType = 'primary',
  playIntro = true,
}) => {
  const bannerIntroRef = useRef<HTMLVideoElement>(null);

  const [introTimeElapsed, setIntroTimeElapsed] = useState(false);
  const [introTimeElapsedTimeout, setIntroTimeElapsedTimeout] = useState<
    number | null
  >(null);

  const [introState, setIntroState] = useState<
    'LOADING' | 'LOADED' | 'PLAYING' | 'ENDED'
  >('LOADING');

  useEffect(() => {
    if (!bannerIntroRef.current) {
      return;
    }

    if (introState === 'LOADED') {
      if (playIntro) {
        bannerIntroRef.current.currentTime = 0;
        bannerIntroRef.current.play();
        const timeout = window.setTimeout(() => {
          setIntroTimeElapsed(true);
          setIntroTimeElapsedTimeout(null);
        }, 400);
        setIntroTimeElapsedTimeout(timeout);
        setIntroState('PLAYING');
      } else if (!introTimeElapsedTimeout) {
        const timeout = window.setTimeout(() => {
          setIntroTimeElapsed(true);
          setIntroTimeElapsedTimeout(null);
        }, 100);
        setIntroTimeElapsedTimeout(timeout);
      }
    } else if (introState === 'ENDED') {
      bannerIntroRef.current.currentTime = 0;
    }

    return () => {
      if (introTimeElapsedTimeout) {
        window.clearTimeout(introTimeElapsedTimeout);
      }
    };
  }, [introState, bannerIntroRef, introTimeElapsedTimeout, playIntro]);

  return (
    <C.StyledSummonerBanner className={bannerType}>
      <C.FadeCondition className={classNames({ show: introTimeElapsed })}>
        <BannerBase rank={rank} showPattern={showPattern} />
      </C.FadeCondition>

      <C.FadeCondition
        className={classNames({ show: !!playIntro && introState !== 'ENDED' })}
      >
        <C.IntroVideo
          src={
            bannerType === 'primary'
              ? Videos.bannerPrimaryIntro
              : Videos.bannerPrimaryIntro
          }
          onLoadedData={() => setIntroState('LOADED')}
          onEnded={() => setIntroState('ENDED')}
          muted
          ref={bannerIntroRef}
        />
      </C.FadeCondition>
    </C.StyledSummonerBanner>
  );
};
