// packages/client/modules/renderer/src/domain/shell/views/Shell.vue
<script setup lang="ts">
import { ref } from 'vue';
import { TitleBar } from '../components';
import { Tooltip, FlyoutFrame } from '@/uikit/overlay/components';

const popperRef = ref<HTMLElement | null>(null);

const showFlyout = ref(false);
</script>

<template>
  <div class="shell">
    <TitleBar />

    <div class="popper-test">
      <div class="popper-inner">
        <button ref="popperRef" @click="showFlyout = !showFlyout">
          Popper go here <br />
          Lorem, ipsum. <br />
          Lorem, ipsum. <br />
          Lorem, ipsum. <br />
          Lorem, ipsum dolor.
        </button>
      </div>
    </div>

    <Tooltip :attach-to="popperRef" placement="top-end">
      <p>
        Hello Lorem, ipsum dolor sit amet consectetur adipisicing elit.
        Suscipit, dolore. 123
      </p>
    </Tooltip>

    <FlyoutFrame
      :show="showFlyout"
      :attach-to="popperRef"
      :close-on-click-outside="true"
      placement="bottom-end"
    >
      <div style="padding: 1rem">
        <h3 style="margin-bottom: 0.5rem">Hello world!</h3>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vitae quas
          <br />
          temporibus quia! Possimus laborum fuga quisquam quia a cumque magni?
        </p>
      </div>
    </FlyoutFrame>
  </div>
</template>

<style lang="scss" scoped>
.shell {
  width: 100%;
  height: 100%;
  position: relative;
  background-color: var(--color-almost-black);
  border: 1px solid var(--color-frame-grey);
  border-top: 2px solid var(--color-gold5);
  overflow: auto;
  contain: content;
}

.popper-test {
  height: 3000px;
  overflow: scroll;
  margin-top: 200px;
  text-align: center;
}

.popper-inner {
  display: flex;
  justify-content: center;
}
</style>

// packages/client/modules/renderer/src/domain/shell/views/shell/Shell.svelte
<script lang="ts">
  import { AnimatedArrowOverlay } from '@/uikit/common/components';
  import { FlyoutFrame, Modal, Tooltip } from '@/uikit/overlay/components';
  import { onMount } from 'svelte';
  import { TitleBar } from '../../components';

  let showModal = true;
  let modalInner: HTMLButtonElement;
  let showFlyoutFrame = false;

  onMount(() => {
    window.electron.window.didLoad();
  });
</script>

<TitleBar />

<button class="parent" on:click={() => (showModal = !showModal)}>
  <p>Hello</p>
  <AnimatedArrowOverlay />
</button>

{#if showModal}
  <Modal
    allyModalHeaderId="modal-head"
    allyModalDescriptionId="modal-body"
    position="bottom"
    topRightCloseButton={{ variant: 'toast', showBackground: true }}
    on:backdrop-click={() => (showModal = false)}
    on:close-click={() => (showModal = false)}
    on:escape-key-up={() => (showModal = false)}
  >
    <div class="modal-inner">
      <h1 id="modal-head">Modal</h1>
      <p class="modal-body">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, porro!
      </p>

      <button
        bind:this={modalInner}
        aria-describedby="modalTooltip"
        on:click={() => (showFlyoutFrame = !showFlyoutFrame)}
      >
        <p>I have some tooltip</p>
      </button>
    </div>

    <Tooltip attachTo={modalInner} id="modalTooltip">
      <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet
        ratione atque perspiciatis aliquam recusandae sed?
      </p>
    </Tooltip>

    {#if showFlyoutFrame}
      <FlyoutFrame attachTo={modalInner}>
        <div class="modal-inner">
          <h4>Hello</h4>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquam,
            nihil?
          </p>
        </div>
      </FlyoutFrame>
    {/if}
  </Modal>
{/if}

<style lang="scss">
  button {
    width: 200px;
    height: 50px;
    position: relative;
    margin-top: 5rem;
    background-color: red;
    p {
      margin: 0;
      padding: 0;
    }
  }

  .modal-inner {
    padding: 1rem;

    h1 {
      margin-bottom: 0.75rem;
    }
  }
</style>
